"use client";

// Lazy chat title generator.
//
// Replaces the placeholder titles ("New chat" / "New artifact" / "Edit · …")
// with a 3-6 word summary of the conversation, generated by Gemma after the
// first complete assistant turn. User-edited titles are never touched.

import { putChat, type StoredChat, type StoredDesigner, type StoredApp, type StoredMessage } from "@/app/db";

const MAX_INFLIGHT = 2;
const inflight = new Map<string, Promise<string | null>>();
const queue: Array<() => void> = [];
let active = 0;

function runQueued<T>(fn: () => Promise<T>): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const start = () => {
      active += 1;
      fn().then(
        (value) => {
          active -= 1;
          drain();
          resolve(value);
        },
        (err) => {
          active -= 1;
          drain();
          reject(err);
        }
      );
    };
    if (active < MAX_INFLIGHT) start();
    else queue.push(start);
  });
}

function drain() {
  while (active < MAX_INFLIGHT && queue.length > 0) {
    const next = queue.shift();
    if (next) next();
  }
}

const PLACEHOLDER_PREFIXES = ["new chat", "new artifact", "untitled chat", "untitled"];
const EDIT_PREFIX = "edit · ";

function isPlaceholderTitle(title: string): boolean {
  const t = title.trim().toLowerCase();
  if (!t) return true;
  if (t.startsWith(EDIT_PREFIX)) return true;
  return PLACEHOLDER_PREFIXES.includes(t);
}

const FALLBACK_MAX_CHARS = 48;

/**
 * Last-resort client-side title when /api/chat-title is unreachable. Take the
 * first sentence of the user's opening message, trim to ~6 words, sentence-case
 * the first letter. Anything is better than leaving "New chat" forever.
 */
function fallbackTitle(firstUserMessage: string): string | null {
  const cleaned = firstUserMessage.replace(/\s+/g, " ").trim();
  if (!cleaned) return null;
  const sentence = cleaned.match(/^(.+?[.!?])(?:\s|$)/)?.[1] ?? cleaned;
  const words = sentence.split(" ").slice(0, 6).join(" ");
  let title = words.replace(/[\s,;:.!?-]+$/, "").trim();
  if (!title) return null;
  if (title.length > FALLBACK_MAX_CHARS) {
    title = title.slice(0, FALLBACK_MAX_CHARS).replace(/[\s,;:.!?-]+$/, "").trim() + "…";
  }
  title = title.charAt(0).toUpperCase() + title.slice(1);
  return isPlaceholderTitle(title) ? null : title;
}

/**
 * True when this chat still has a placeholder title that hasn't been manually
 * renamed and we haven't already generated one for the current conversation.
 */
export function shouldGenerateChatTitle(chat: StoredChat): boolean {
  if (chat.titleSource === "user") return false;
  if (chat.titleSource === "gemma") return false;
  return isPlaceholderTitle(chat.title);
}

type Target = { designer?: StoredDesigner; app?: StoredApp };

async function postTitle(
  firstUserMessage: string,
  firstAssistantSnippet: string | undefined,
  target: Target
): Promise<string | null> {
  const targetMeta = target.designer
    ? { kind: "designer", name: target.designer.name }
    : target.app
      ? { kind: "app", name: target.app.name }
      : undefined;
  const res = await fetch("/api/chat-title", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      firstUserMessage,
      firstAssistantSnippet,
      target: targetMeta,
    }),
  });
  if (!res.ok) return null;
  const data = (await res.json()) as { title?: string; error?: string };
  const title = (data.title ?? "").trim();
  return title || null;
}

/**
 * Generate (or reuse an inflight) title for `chat` based on its messages and
 * persist it. Concurrent calls coalesce; failures are silent.
 *
 * Caller is responsible for first checking `shouldGenerateChatTitle` and that
 * messages contain at least one finished assistant turn.
 */
export function generateChatTitle(
  chat: StoredChat,
  messages: StoredMessage[],
  target: Target
): Promise<string | null> {
  const existing = inflight.get(chat.id);
  if (existing) return existing;

  const firstUser = messages.find((m) => m.role === "user");
  const firstAssistant = messages.find(
    (m) => m.role === "assistant" && !m.streamId && m.kind !== "summary"
  );
  if (!firstUser?.content?.trim()) {
    return Promise.resolve(null);
  }

  const promise = runQueued(async () => {
    let title: string | null = null;
    try {
      title = await postTitle(
        firstUser.content,
        firstAssistant?.content?.slice(0, 600),
        target
      );
    } catch {
      title = null;
    }
    if (!title) title = fallbackTitle(firstUser.content);
    if (!title) return null;
    try {
      await putChat({
        ...chat,
        title,
        titleSource: "gemma",
        titleUpdatedAt: Date.now(),
        updatedAt: Date.now(),
      });
    } catch {
      // best-effort
    }
    return title;
  }).finally(() => {
    inflight.delete(chat.id);
  });

  inflight.set(chat.id, promise);
  return promise;
}
