"use client";

// Native, host-rendered view for a "Research" app. Research apps are a known
// structured type whose data lives on app.state (query/columns/idKeys/records),
// so we render the table directly in the host instead of inside the sandboxed
// artifact iframe. That makes the table ALWAYS show - immune to a mangled
// designer VFS, a failed build, or the iframe's flaky first paint (the cause of
// the "research app is just blank" bug). Refresh runs the same deep-research
// engine the chat viewer uses (/api/research/structured/run -> resume) and
// merges new rows by identity.
//
// ⚠️ THIS IS A GENERIC, DOMAIN-AGNOSTIC PLATFORM TEMPLATE. It renders ANY
// research table (a query + columns + records). Do NOT bake domain/product
// features into it (no job-search resume/outreach, no CRM contacts, no sales
// pipeline, etc.). Anything tied to a specific use case is a PRODUCT FEATURE and
// belongs in a user-built artifact app (generated by prompting the model in the
// builder, using the artifact SDK), not here. Keep additions generic enough that
// every research app - whatever its subject - benefits. See CLAUDE.md
// ("Platform vs product").

import { useCallback, useEffect, useRef, useState } from "react";
import {
  Loader2,
  RefreshCw,
  AlertTriangle,
  Square,
  ArrowDownWideNarrow,
  X,
  Sparkles,
  Pencil,
  Check,
  Trash2,
} from "lucide-react";
import type { ResearchColumn, StoredApp } from "@/app/db";

type FlatRecord = { id: string } & Record<string, unknown>;

function norm(s: unknown): string {
  return String(s == null ? "" : s).toLowerCase().replace(/[^a-z0-9]+/g, "").slice(0, 80);
}
function identity(rec: FlatRecord, idKeys: string[]): string {
  const keys = idKeys.length ? idKeys : Object.keys(rec).filter((k) => k !== "id");
  return keys.map((k) => norm(rec[k])).filter(Boolean).join("|");
}
function hasContent(rec: FlatRecord, columns: ResearchColumn[]): boolean {
  return columns.some((c) => {
    const v = rec[c.key];
    return typeof v === "number" || (typeof v === "string" && v.trim().length > 0);
  });
}
// Merge incoming run rows into the existing table: dedupe by identity columns
// (fill blanks on a match), drop empty rows, count the genuinely new ones.
function mergeRows(
  existing: FlatRecord[],
  incoming: FlatRecord[],
  columns: ResearchColumn[],
  idKeys: string[]
): { rows: FlatRecord[]; added: number } {
  const byId = new Map<string, FlatRecord>();
  const order: string[] = [];
  for (const r of existing) {
    const id = identity(r, idKeys) || r.id;
    if (id && !byId.has(id)) {
      byId.set(id, r);
      order.push(id);
    }
  }
  let added = 0;
  for (const raw of incoming) {
    if (!raw || typeof raw !== "object") continue;
    const rec: FlatRecord = { id: "" };
    for (const c of columns) rec[c.key] = raw[c.key] == null ? "" : raw[c.key];
    if (!hasContent(rec, columns)) continue;
    let id = identity(rec, idKeys);
    if (!id) id = typeof raw.id === "string" && raw.id ? raw.id : "r" + (order.length + 1);
    rec.id = id;
    const prev = byId.get(id);
    if (prev) {
      const merged: FlatRecord = { ...prev };
      for (const c of columns) {
        const v = rec[c.key];
        if (v !== "" && v != null) merged[c.key] = v;
      }
      merged.id = id;
      byId.set(id, merged);
    } else {
      byId.set(id, rec);
      order.push(id);
      added++;
    }
  }
  return { rows: order.map((id) => byId.get(id)!), added };
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export function ResearchAppView({
  app,
  refreshSignal,
  onPersistRecords,
  onPersistPending,
}: {
  app: StoredApp;
  /** Bumped by the header Refresh button to trigger a run. */
  refreshSignal: number;
  /** Persist merged records (+ updatedAt) back to app.state. */
  onPersistRecords: (records: FlatRecord[]) => void;
  /** Persist (or clear) the in-flight run's streamId on app.state, so a run
   *  survives closing the tab: on the next open we resume polling it. */
  onPersistPending?: (streamId: string | null) => void;
}) {
  const st = app.state ?? {};
  const query = typeof st.query === "string" ? st.query : "";
  const columns = (Array.isArray(st.columns) ? st.columns : []) as ResearchColumn[];
  const idKeys = (Array.isArray(st.idKeys) ? st.idKeys : []) as string[];
  const schema = st.schema;
  const records = (Array.isArray(st.records) ? st.records : []) as FlatRecord[];

  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [added, setAdded] = useState(0);
  const [startedAt, setStartedAt] = useState(0);
  const [now, setNow] = useState(() => 0);
  const pollingRef = useRef<string | null>(null);
  const runningRef = useRef(false);

  useEffect(() => {
    if (!running) return;
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, [running]);

  // Refs so the long-poll + scheduled pickup always merge against the latest
  // props without re-subscribing.
  const recordsRef = useRef(records);
  recordsRef.current = records;
  const colsRef = useRef(columns);
  colsRef.current = columns;
  const idKeysRef = useRef(idKeys);
  idKeysRef.current = idKeys;
  const persistRef = useRef(onPersistRecords);
  persistRef.current = onPersistRecords;
  const persistPendingRef = useRef(onPersistPending);
  persistPendingRef.current = onPersistPending;

  // Poll the resumable result endpoint until terminal, then merge by identity.
  // Shared by a fresh Refresh and the resume-on-open path, so both behave the
  // same. Merges against the LATEST records (via refs) so a result that lands
  // after other edits still folds in cleanly.
  const pollAndMerge = useCallback(async (streamId: string): Promise<void> => {
    pollingRef.current = streamId;
    while (pollingRef.current === streamId) {
      let r: Response;
      try {
        r = await fetch(`/api/query/resume/${encodeURIComponent(streamId)}`);
      } catch {
        await sleep(2000);
        continue;
      }
      if (r.status === 504) {
        await sleep(1500);
        continue;
      }
      const payload = (await r.json().catch(() => ({}))) as {
        records?: { id?: string; fields?: Record<string, unknown> }[];
        error?: string;
      };
      if (!r.ok || payload.error) throw new Error(payload.error ?? `Run failed (${r.status})`);
      const incoming: FlatRecord[] = Array.isArray(payload.records)
        ? payload.records.map((rec) => ({ id: String(rec.id ?? ""), ...(rec.fields ?? {}) }))
        : [];
      const m = mergeRows(recordsRef.current, incoming, colsRef.current, idKeysRef.current);
      setAdded(m.added);
      persistRef.current(m.rows);
      return;
    }
  }, []);

  const run = useCallback(async () => {
    if (runningRef.current || !query) return;
    runningRef.current = true;
    setRunning(true);
    setError(null);
    setAdded(0);
    setStartedAt(Date.now());
    setNow(Date.now());
    try {
      const res = await fetch("/api/research/structured/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query,
          columns: columns.length ? columns : undefined,
          idKeys: idKeys.length ? idKeys : undefined,
          priorRecords: records.length
            ? records.map((r) => {
                const { id, ...fields } = r;
                return { id, fields };
              })
            : undefined,
          model: app.model || undefined,
        }),
      });
      const data = (await res.json().catch(() => ({}))) as { streamId?: string; error?: string };
      if (!res.ok || !data.streamId) throw new Error(data.error ?? `Failed to start (${res.status})`);
      // Persist the streamId so the run survives a tab close: the worker keeps
      // running server-side (3-day result TTL) and we resume polling on reopen.
      persistPendingRef.current?.(data.streamId);
      await pollAndMerge(data.streamId);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      pollingRef.current = null;
      runningRef.current = false;
      setRunning(false);
      persistPendingRef.current?.(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query, columns, idKeys, records, app.model, pollAndMerge]);

  // Resume an in-flight run from a previous session: app.state may carry a
  // pending streamId whose worker finished (or is still going) while the tab was
  // closed. Re-attach once on mount and merge the result when it lands - this is
  // what makes "run a query, close the browser, come back later" actually add
  // the data.
  const resumedRef = useRef(false);
  useEffect(() => {
    if (resumedRef.current || runningRef.current) return;
    const pending = (app.state as { pendingRunStreamId?: unknown } | undefined)?.pendingRunStreamId;
    if (typeof pending !== "string" || !pending) return;
    resumedRef.current = true;
    runningRef.current = true;
    setRunning(true);
    setStartedAt(Date.now());
    setNow(Date.now());
    void (async () => {
      try {
        await pollAndMerge(pending);
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
      } finally {
        pollingRef.current = null;
        runningRef.current = false;
        setRunning(false);
        persistPendingRef.current?.(null);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [app.id]);

  // Header Refresh button bumps refreshSignal.
  const lastSignal = useRef(refreshSignal);
  useEffect(() => {
    if (refreshSignal !== lastSignal.current) {
      lastSignal.current = refreshSignal;
      void run();
    }
  }, [refreshSignal, run]);

  const stop = () => {
    pollingRef.current = null;
    runningRef.current = false;
    setRunning(false);
  };

  // --- pick up COMPLETED scheduled runs --------------------------------------
  // Scheduled refreshes run server-side and land in the schedule store. The old
  // iframe template polled them; the native view must too, or a scheduled run's
  // data "never populates". Catch up on mount + poll while open, merging by id.
  const lastSchedRef = useRef(0);
  useEffect(() => {
    let cancelled = false;
    const poll = async () => {
      try {
        const r = await fetch(`/api/schedules/${encodeURIComponent(app.id)}`);
        if (!r.ok || cancelled) return;
        const snap = (await r.json()) as {
          status?: string;
          runAt?: number;
          result?: { records?: FlatRecord[] };
        };
        const at = typeof snap.runAt === "number" ? snap.runAt : 0;
        const recs =
          snap.result && Array.isArray(snap.result.records) ? snap.result.records : null;
        if (snap.status === "complete" && recs && at > lastSchedRef.current) {
          lastSchedRef.current = at;
          const m = mergeRows(recordsRef.current, recs, colsRef.current, idKeysRef.current);
          if (m.added > 0 || m.rows.length !== recordsRef.current.length) {
            setAdded(m.added);
            persistRef.current(m.rows);
          }
        }
      } catch {
        /* best-effort */
      }
    };
    void poll();
    const t = setInterval(poll, 15000);
    return () => {
      cancelled = true;
      clearInterval(t);
    };
  }, [app.id]);

  // --- AI sort/rank pass over the collected rows -----------------------------
  // Separate from research collection: research COLLECTS rows; this RANKS the
  // existing rows (reorders best-first) in one LLM pass. It never touches the
  // research run path, so scheduled/manual refresh keep working.
  const [sorting, setSorting] = useState(false);
  const [sortCriteria, setSortCriteria] = useState("");
  const aiSort = useCallback(async () => {
    if (sorting || records.length === 0) return;
    setSorting(true);
    setError(null);
    try {
      const res = await fetch("/api/research/structured/rank", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          records,
          columns,
          instruction: sortCriteria.trim() || undefined,
          // No model: the rank route uses a fast model. The heavy research model
          // thinks for minutes and times the sort out.
        }),
      });
      const data = (await res.json().catch(() => ({}))) as { order?: unknown[]; error?: string };
      if (!res.ok || !Array.isArray(data.order)) {
        throw new Error(data.error ?? `Sort failed (${res.status})`);
      }
      const byId = new Map(records.map((r) => [r.id, r]));
      const ordered: FlatRecord[] = [];
      for (const id of data.order) {
        const r = byId.get(String(id));
        if (r) {
          ordered.push(r);
          byId.delete(String(id));
        }
      }
      for (const r of byId.values()) ordered.push(r); // unranked rows keep their place at the end
      onPersistRecords(ordered);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setSorting(false);
    }
  }, [sorting, records, columns, app.model, sortCriteria, onPersistRecords]);

  // --- per-row detail drawer: view fields + ask the model about this row -----
  const [selected, setSelected] = useState<FlatRecord | null>(null);
  const [askText, setAskText] = useState("");
  const [askWeb, setAskWeb] = useState(true);
  const [asking, setAsking] = useState(false);
  const [qa, setQa] = useState<{ q: string; a: string }[]>([]);
  const [editMode, setEditMode] = useState(false);

  // Update one record in place and persist. Keeps the open drawer's `selected`
  // in sync so edits show immediately.
  const updateRecord = useCallback((rowId: string, patch: Record<string, unknown>) => {
    const next = recordsRef.current.map((r) => (r.id === rowId ? { ...r, ...patch } : r));
    persistRef.current(next);
    setSelected((cur) => (cur && cur.id === rowId ? { ...cur, ...patch } : cur));
  }, []);
  const deleteRow = useCallback((rowId: string) => {
    persistRef.current(recordsRef.current.filter((r) => r.id !== rowId));
    setSelected((cur) => (cur && cur.id === rowId ? null : cur));
  }, []);

  const openRow = (rec: FlatRecord) => {
    setSelected(rec);
    // Restore this row's prior Q&A history so the drawer is durable, not a
    // scratchpad.
    setQa(Array.isArray(rec.qaLog) ? (rec.qaLog as { q: string; a: string }[]) : []);
    setAskText("");
  };

  // Title for the drawer header = the row's first column value (its identity).
  const titleOf = (rec: FlatRecord) =>
    columns[0] ? String(rec[columns[0].key] ?? "") : "";

  // Ask the model a free-form question about this row (optionally with web
  // search). Domain-agnostic: it just answers about the row's fields.
  const ask = async () => {
    if (asking || !selected || !askText.trim()) return;
    const q = askText.trim();
    setAsking(true);
    try {
      const res = await fetch("/api/research/structured/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          row: selected,
          columns,
          instruction: q,
          webSearch: askWeb,
          model: app.model || undefined,
        }),
      });
      const d = (await res.json().catch(() => ({}))) as { answer?: string; error?: string };
      if (!res.ok) throw new Error(d.error ?? `Ask failed (${res.status})`);
      const nextQa = [...qa, { q, a: d.answer ?? "" }];
      setQa(nextQa);
      if (selected) updateRecord(selected.id, { qaLog: nextQa }); // persist Q&A per row
      setAskText("");
    } catch (e) {
      setQa((prev) => [...prev, { q, a: `Error: ${e instanceof Error ? e.message : String(e)}` }]);
    } finally {
      setAsking(false);
    }
  };

  const elapsed = running && startedAt ? Math.max(0, now - startedAt) : 0;
  const elapsedLabel = `${Math.floor(elapsed / 60000)}:${String(
    Math.floor((elapsed % 60000) / 1000)
  ).padStart(2, "0")}`;

  return (
    <div className="relative flex h-full min-h-0 flex-col bg-[#161412] text-[#f1ece2]">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 px-4 py-2.5">
        <div className="min-w-0">
          <div className="truncate text-sm font-medium" title={query}>
            {query || "Research"}
          </div>
          <div className="text-[11px] text-white/50">
            {running
              ? `Researching… ${elapsedLabel} · runs in the background`
              : `${records.length} result${records.length === 1 ? "" : "s"}${
                  added > 0 ? ` · +${added} new` : ""
                }`}
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          {!running && records.length > 0 && (
            <>
              <input
                value={sortCriteria}
                onChange={(e) => setSortCriteria(e.target.value)}
                placeholder="Rank by… (e.g. best fit, highest equity)"
                disabled={sorting}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    void aiSort();
                  }
                }}
                className="hidden w-52 rounded-md border border-white/15 bg-white/5 px-2.5 py-1.5 text-xs text-white placeholder:text-white/40 outline-none focus:border-white/30 sm:block"
              />
              <button
                type="button"
                onClick={() => void aiSort()}
                disabled={sorting}
                title="Let AI rank/sort the collected rows (does not re-run research)"
                className="tap inline-flex items-center gap-1 rounded-md border border-white/15 px-2.5 py-1.5 text-xs text-white/85 hover:bg-white/5 disabled:opacity-60"
              >
                {sorting ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <ArrowDownWideNarrow className="h-3.5 w-3.5" />
                )}
                AI sort
              </button>
              <button
                type="button"
                onClick={() => setEditMode((e) => !e)}
                title={editMode ? "Done editing" : "Edit / fix cells, delete rows"}
                className={
                  "tap inline-flex items-center gap-1 rounded-md border px-2.5 py-1.5 text-xs disabled:opacity-60 " +
                  (editMode
                    ? "border-[#6fae93]/50 bg-[#6fae93]/15 text-[#9fd6c0]"
                    : "border-white/15 text-white/85 hover:bg-white/5")
                }
              >
                {editMode ? <Check className="h-3.5 w-3.5" /> : <Pencil className="h-3.5 w-3.5" />}
                {editMode ? "Done" : "Edit"}
              </button>
            </>
          )}
          {running ? (
            <button
              type="button"
              onClick={stop}
              className="tap inline-flex items-center gap-1 rounded-md border border-white/15 px-2.5 py-1.5 text-xs text-white/80 hover:bg-white/5"
            >
              <Square className="h-3 w-3 fill-current" /> Stop
            </button>
          ) : (
            <button
              type="button"
              onClick={() => void run()}
              disabled={!query}
              className="tap inline-flex items-center gap-1 rounded-md bg-[#e07358] px-3 py-1.5 text-xs font-semibold text-[#1c140f] disabled:opacity-60"
            >
              <RefreshCw className="h-3.5 w-3.5" /> Refresh
            </button>
          )}
        </div>
      </div>

      {error && (
        <div className="flex items-start gap-2 border-b border-white/10 bg-[#e07358]/10 px-4 py-2 text-xs text-[#f0a78f]">
          <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {columns.length > 0 && records.length > 0 ? (
        <div className="min-h-0 flex-1 overflow-auto">
          <table className="w-full border-collapse text-sm">
            <thead className="sticky top-0 bg-[#14101f]">
              <tr>
                {editMode && <th className="w-8 border-b border-white/10 px-2 py-2" />}
                {columns.map((c) => (
                  <th
                    key={c.key}
                    className="border-b border-white/10 px-3 py-2 text-left text-[11px] font-medium uppercase tracking-wide text-white/55"
                  >
                    {c.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {records.map((rec) => (
                <tr
                  key={rec.id}
                  onClick={editMode ? undefined : () => openRow(rec)}
                  className={editMode ? "" : "cursor-pointer hover:bg-white/[0.05]"}
                  title={editMode ? undefined : "Open row · view fields · ask AI"}
                >
                  {editMode && (
                    <td className="border-b border-white/[0.06] px-2 py-2 align-top">
                      <button
                        type="button"
                        onClick={() => deleteRow(rec.id)}
                        title="Delete this row"
                        className="tap rounded p-1 text-white/35 hover:bg-white/10 hover:text-[#f0a78f]"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </td>
                  )}
                  {columns.map((c) => (
                    <td key={c.key} className="border-b border-white/[0.06] px-3 py-2 align-top">
                      {editMode ? (
                        <textarea
                          key={`${rec.id}:${c.key}`}
                          defaultValue={rec[c.key] == null ? "" : String(rec[c.key])}
                          onBlur={(e) => {
                            const v = e.target.value;
                            const cur = rec[c.key] == null ? "" : String(rec[c.key]);
                            if (v !== cur) updateRecord(rec.id, { [c.key]: v });
                          }}
                          rows={1}
                          className="w-full min-w-[8rem] resize-y rounded border border-white/15 bg-white/5 px-1.5 py-1 text-[13px] text-white outline-none focus:border-white/30"
                        />
                      ) : (
                        <Cell value={rec[c.key]} type={c.type} />
                      )}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="flex flex-1 flex-col items-center justify-center gap-2 px-4 py-10 text-center">
          {running ? (
            <>
              <Loader2 className="h-5 w-5 animate-spin text-[#6fae93]" />
              <div className="text-sm">Researching… {elapsedLabel}</div>
              <div className="text-[11px] text-white/50">Deep research usually takes 1-2 minutes.</div>
            </>
          ) : (
            <>
              <div className="text-sm text-white/70">No results yet.</div>
              <div className="text-[11px] text-white/50">Hit Refresh to run the research.</div>
            </>
          )}
        </div>
      )}

      {/* per-row detail drawer */}
      {selected && (
        <>
          <div
            className="absolute inset-0 z-20 bg-black/40"
            onClick={() => setSelected(null)}
          />
          <div className="absolute inset-y-0 right-0 z-30 flex w-full max-w-md flex-col border-l border-white/10 bg-[#1b1714] shadow-2xl">
            <div className="flex items-center justify-between gap-2 border-b border-white/10 px-4 py-3">
              <div className="min-w-0">
                <div className="truncate text-sm font-semibold">
                  {titleOf(selected) || "Row"}
                </div>
              </div>
              <button
                type="button"
                onClick={() => setSelected(null)}
                className="tap rounded-md p-1 text-white/60 hover:bg-white/10 hover:text-white"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="min-h-0 flex-1 overflow-auto px-4 py-3 text-sm">
              {/* all fields */}
              <div className="space-y-2">
                {columns.map((c) => {
                  const v = selected[c.key];
                  if (v == null || String(v) === "") return null;
                  return (
                    <div key={c.key}>
                      <div className="text-[10px] uppercase tracking-wide text-white/40">
                        {c.label}
                      </div>
                      <div className="text-white/85">
                        <Cell value={v} type={c.type} />
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* ask anything about this row */}
              <div className="mt-4">
                <div className="mb-1 text-[10px] uppercase tracking-wide text-white/40">
                  Ask about this row
                </div>
                {qa.map((t, i) => (
                  <div key={i} className="mb-2 rounded-lg border border-white/10 bg-white/[0.03] p-2.5">
                    <div className="text-[11px] font-medium text-white/60">{t.q}</div>
                    <div className="mt-1 whitespace-pre-wrap text-white/85">{t.a}</div>
                  </div>
                ))}
                <div className="flex items-center gap-1.5">
                  <input
                    value={askText}
                    onChange={(e) => setAskText(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        void ask();
                      }
                    }}
                    placeholder="e.g. summarize this row, or verify a field"
                    disabled={asking}
                    className="flex-1 rounded-md border border-white/15 bg-white/5 px-2.5 py-1.5 text-xs outline-none focus:border-white/30"
                  />
                  <button
                    type="button"
                    onClick={() => void ask()}
                    disabled={asking || !askText.trim()}
                    className="tap inline-flex items-center gap-1 rounded-md border border-white/15 px-2.5 py-1.5 text-xs text-white/85 hover:bg-white/5 disabled:opacity-50"
                  >
                    {asking ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <Sparkles className="h-3.5 w-3.5" />
                    )}
                    Ask
                  </button>
                </div>
                <label className="mt-1.5 flex items-center gap-1.5 text-[11px] text-white/50">
                  <input
                    type="checkbox"
                    checked={askWeb}
                    onChange={(e) => setAskWeb(e.target.checked)}
                    className="accent-[#6fae93]"
                  />
                  Search the web for fresh information
                </label>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function Cell({ value, type }: { value: unknown; type?: ResearchColumn["type"] }) {
  const s = value == null ? "" : String(value);
  if (!s) return <span className="text-white/25">—</span>;
  if (type === "link" && /^https?:\/\//i.test(s)) {
    let label = s;
    try {
      label = new URL(s).hostname.replace(/^www\./, "");
    } catch {
      /* keep raw */
    }
    return (
      <a href={s} target="_blank" rel="noreferrer" className="text-[#93c5fd] underline">
        {label}
      </a>
    );
  }
  return <span className="whitespace-pre-wrap break-words">{s}</span>;
}
